#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ "$1" = install ] || [ "$1" = upgrade ]; then
	if [ -e "/etc/init.d/apport" ] && [ -L "/etc/init.d/apport" ] \
	   && [ $(readlink -f "/etc/init.d/apport") = /lib/init/upstart-job ]
	then
		rm -f "/etc/init.d/apport"
	fi
fi
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/apport/native-origins.d/lts-q-backports 2.5.1-0ubuntu8~ -- "$@"
# End automatically added section
