#!/bin/sh -e
#
# postinst script for the Debian GNU/Linux libgsl0 package
#
# Written and GPL'ed by Dirk Eddelbuettel <edd@debian.org>   

# Automatically added by dh_makeshlibs
if [ "$1" = "configure" ]; then
	ldconfig
fi
# End automatically added section


case "$1" in

    configure)     
	;;

    upgrade|abort-upgrade|abort-remove|abort-deconfigure)
	;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        ;;

esac

exit 0                 

