#!/bin/bash

set -e

if [ "$1" = "purge" ]; then
  rmdir /etc/mysql 2>/dev/null || true
  update-alternatives --remove-all my.cnf
fi

# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/mysql/my.cnf 5.6.22-1~ mysql-common -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/mysql/conf.d/.keepme 5.6.22-1~ mysql-common -- "$@"
# End automatically added section

